INSERT INTO Figuras (FIG_NOMBRE, FIG_TIPO, FIG_LADO) VALUES ("cua1", 1, 10.0);
INSERT INTO Figuras (FIG_NOMBRE, FIG_TIPO, FIG_RADIO) VALUES ("cir1", 2, 10.0);
INSERT INTO Figuras (FIG_NOMBRE, FIG_TIPO, FIG_BASE, FIG_ALTURA) VALUES ("triangulo1", 4, 10.0, 8.4);
INSERT INTO Figuras (FIG_NOMBRE, FIG_TIPO, FIG_BASE, FIG_ALTURA) VALUES ("rect1", 3, 12.3, 8.4);
INSERT INTO Figuras (FIG_NOMBRE, FIG_TIPO, FIG_LADO, FIG_NUMLADOS, FIG_APOTEMA) VALUES ("polig1", 5, 10.0, 6, 6.2);